version: "3"

services:
  # db:
  #   container_name: db
  #   image: postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"
  rustapp:
    image: rustapp
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000
    volumes:
      - rustapp_data:/user/local/bin/tasks
    depends_on:
      - rabbitmq
  ngrok:
    image: wernight/ngrok
    command: sh -c "ngrok authtoken ${NGROK_AUTH_TOKEN} && ngrok http --domain=${DOMAIN} rustapp:5000"
    env_file:
      - .env
    ports:
      - "4040:4040"
    depends_on:
      - rustapp

volumes:
  # pgdata: {}
  rabbitmq_data:
    driver: local
  rustapp_data:
    driver: local
