version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    ports:
      - "15672:15672"
      - "5672:5672"

  # judge-ma-di:
  #   container_name: judge-ma-di
  #   build:
  #     dockerfile: dockerfile
  #     args:
  #       POSTGRES_URL: postgres://default:3gDyWUbe0mZR@ep-steep-flower-a1w69dji-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require
  #   ports:
  #     - 5000:5000

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: "root" # Set PostgreSQL user
  #     POSTGRES_PASSWORD: "root" # Set PostgreSQL password
  #     POSTGRES_DB: "root" # Set default database
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com" # Set pgAdmin email
  #     PGADMIN_DEFAULT_PASSWORD: "pgadminpassword" # Set pgAdmin password
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

volumes:
  rabbitmq_data:
    driver: local
  # postgres_data:
  #   driver: local
