version: "3"

services:
  # db:
  #   container_name: db
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    ports:
      - "15672:15672"
      - "5672:5672"
  rustapp:
    image: rustapp
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    environment:
      POSTGRES_URL: postgres://postgres:postgres@localhost:5432
      MAX_WORKER: 1
      ALLOW_ORIGIN: http://localhost:3000
      RBMQ_URL: amqp://root:root@rabbitmq:5672
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
  ngrok:
    image: wernight/ngrok
    command: sh -c "ngrok authtoken YOUR_AUTH_TOKEN && ngrok http --domain=YOUR_DOMAIN rustapp:5000"
    ports:
      - "4040:4040"
    depends_on:
      - rustapp

volumes:
  # pgdata: {}
  rabbitmq_data:
    driver: local
  rustapp_data:
    driver: local
